title: Happy Blog
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "d4rpell"
  email: "someone@somewebsite.somedomain"
  url: "https://d4rpell.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "d4rpell"
year : "2022"
